### ISSUE TITLE
Issue on page /pre-hunt/data_documentation.html

### ISSUE THREAD

**Issue by m-terlinde** [OTRF/ThreatHunter-Playbook#48]
Hey Roberto,

thanks for all the references!
The page mentioned above references [this file](https://github.com/OTRF/OSSEM/blob/master/source/data_dictionaries/windows/sysmon/events/event-1.yml), but the link is dead.

The sentence in question is "Translate useful fields to a YAML file as shown here."

Furthermore, in the section `References`, there is an `)` too much.

Thanks again!
Matthias

**Comment by Cyb3rWard0g** [comment]
Thank you for letting me know Matthias! I appreciate you taking the time :)
