### ISSUE TITLE
Issues with APT 29 Free Telemetry Notebook

### ISSUE THREAD

**Issue by harperaa** [OTRF/ThreatHunter-Playbook#50]
The URL for Decompress Dataset is incorrect, had to use the following instead.
https://github.com/OTRF/Security-Datasets/raw/master/datasets/compound/apt29/day1/apt29_evals_day1_manual.zip

Btw, great work to you and the team.  Standby for heavy use of OTRF tools in upcoming revision of Gray Hat Hacking book, in Jan.

**Comment by harperaa** [comment]
I was using the binder link, btw.

**Comment by Cyb3rWard0g** [comment]
Thank you very much for the feedback and for letting us know about this issue. I will update some of those links. They should have been updated with a script but we missed this one. Looking forward to the Gray Hat hacking book :) Happy to see our contributions to the community helping others :)
